### ISSUE TITLE
Implement environment variable setup in session creation UI

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-console#210]
Some use cases include setting environment variables manually when launching new sessions, such as `HTTP_PROXY` or other settings.

Phase 1:
* [x] Ability to add/remove/change environment variables as a table of input field pairs.

Phase 2:
* [ ] Ability to store and load frequently used envrionment variable sets. It could be implemented using the client-side local storage.

**Comment by inureyes** [comment]
Covered in #902 #903
