### ISSUE TITLE
User settings page

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#319]
* Provide user settings page
 * User settings page will cover:
   * Web preferences
   * App preferences

## TODO
 * [x] Create tab for user settings

**Comment by inureyes** [comment]
TODO : change 'fifo' to {'fifo'}

**Comment by inureyes** [comment]
@adrysn  I'll merge it first. After that, I'll turn the tab off and rebranch for log job.

**Comment by inureyes** [comment]
Now refer the feature/#319-user-settings-page-editor branch.

**Comment by inureyes** [comment]
@adrysn  and my opinion is using https://github.com/vanillawc/wc-codemirror instead of codemirror.

**Comment by adrysn** [comment]
Okay, I'll try it.
