### ISSUE TITLE
Update JavaScript SDK to accept v5 specification

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#323]
* Update JavaScript SDK to accept v5 specification

## Requirements
 * [x] Check manager version
 * [x] Let `/kernel/` to `/session/` for v5
 * [x] Let `kernelId` to `sessionId` for v5

**Comment by achimnol** [comment]
Please refer how the Python SDK handles the combination of API path prefix, JSON argument, and GQL field name differences: https://github.com/lablup/backend.ai-client-py/commit/554e9f3da576e6f911052ffbaee2b062050027c7
