### ISSUE TITLE
Upgrade session launch UI

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#374]
CHANGED: `Version pull-down menu does not update automatically on session start dialog` to `Upgrade session launch UI`, due to the heavy modification on this issue. 

 * Version pull-down menu does not update automatically on session start dialog
 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/949915/75081147-947aa900-5551-11ea-84b0-5d3d05ba9b30.png">

 * When I choose TensorFlow and choose Python, version remains TensorFlow one.

**Comment by adrysn** [comment]
@lizable I think there are some issues that need to be handled.

- [x] Preserve user-selected Environment/Version when re-open the session creation dialog
  - Users usually launch the same Environment/Version image repeatedly.
- [ ] The state of LAUNCH button is not updated when image changes.
  - Steps to reproduce:
    - Select a group that can access non-GPU agents only.
    - Open session creation dialog.
    - Select an image that utilizes GPU (eg: TensorFlow:2.0-py36-cuda9). LAUNCH button should be disabled with "NOT ENOUGH RESOURCE" message since no agents provide GPU resource.
    - Now, choose a non-GPU image, such as python:3.6-ubuntu18.04. The LAUNCH button should be appeared, but "NOT ENOUGH RESOURCE' message is still there in a disabled state.
    - If there are multiple Versions, and can choose other version of the same envrionment, the button is not activated with "LAUNCH" message.
    - Conversely, non-GPU image is selected first (LAUNCH button activated) and then choose GPU image, LAUNCH button still in an activated state.
  - Refer to the image below.
  ![image](https://user-images.githubusercontent.com/7539358/75312503-71c3f980-589d-11ea-96c9-7ecd84d76feb.png)
- [ ] In console's `config.toml`, there is a field `defaultSessionEnvironment` in `general` section. This field determines the default image to be selected when you open the session creation dialog first time. For example, if you set the field with `index.docker.io/lablup/python:3.6-ubuntu18.04`, Python 3.6-ubuntu18.04 environment/version should be the default one. This does not work anymore, and if you set any value to the field, no values are selected in the session creation dialog.
  ![image](https://user-images.githubusercontent.com/7539358/75313057-11ce5280-589f-11ea-8523-495fa1439408.png)

### Minor issues
- [ ] Some images have empty black tags in the Requirements field.
    ![image](https://user-images.githubusercontent.com/7539358/75312043-16ddd280-589c-11ea-98d0-012d062020ed.png)

**Comment by adrysn** [comment]
I think I resolved the second issue (The state of LAUNCH button is not updated when image changes.). However, there still is a remaining issue.

- [ ] Changing project does not update the resource group in session launch dialog.
  - Displayed value does not match actually selected value.
  ![image](https://user-images.githubusercontent.com/7539358/75361071-1411ca80-58fa-11ea-8c37-2f1dc662d90e.png)

**Comment by adrysn** [comment]
Also, black tag issue is not yet resolved.
![image](https://user-images.githubusercontent.com/7539358/75361279-69e67280-58fa-11ea-9467-ae612cf3c891.png)

**Comment by adrysn** [comment]
This may be my personal preferences, but I don't like the red lines all over the dialogs: Environments, Version, Resource Group, and Folders to mount.

![image](https://user-images.githubusercontent.com/7539358/75361413-97332080-58fa-11ea-83bb-17a4266ee8c5.png)

**Comment by inureyes** [comment]
9b3b5294f6e44

**Comment by inureyes** [comment]
Prevent error when for Projects without any scaling group 9b3b5294f6e44
