### ISSUE TITLE
Cannot logout on settings / log page

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#399]
User cannot logout on settings / log page.

![image](https://user-images.githubusercontent.com/949915/75660858-a4ac2a00-5caf-11ea-9a15-ff029c3fdaf0.png)

In this page, logout menu on top-right corner does not work.

**Comment by lizable** [comment]
I wonder if this happens in a certain routine.
What I've found out is that it works well when I move click event into mwc-menu-items tag, instead of anchor tag.
