### ISSUE TITLE
vFolder file download not working on iOS/iPadOS

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai-console#465]
Due to mobile Safari's restriction, programmatically invoking click event to dummy anchor (`a.click()`) is not working. How do you think about adding fallback method for those devices by opening popup window of vFolder download URL?

**Comment by inureyes** [comment]
Actually, Safari for iOS have some issues with shadowDOM including weird scroll target issue too. Waiting for the browser update or apply the fallback. It is always the problem.

 I'll find out the latter way.
