### ISSUE TITLE
Change 'About' to 'About Backend.AI'

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#694]
* Change 'About' to 'About Backend.AI'
 * Change '대하여' to 'Backend.AI에 대하여'

<img width="228" alt="image" src="https://user-images.githubusercontent.com/949915/92066580-36baf980-eddd-11ea-9d57-a59ba54106e7.png">

**Comment by swapniljha001** [comment]
Can you tell which file needs to be edited in order to resolve this issue?

**Comment by lizable** [comment]
> Can you tell which file needs to be edited in order to resolve this issue?

You can find it in backend-ai-console in src/components/ of this repository. (you can see the link below)
https://github.com/lablup/backend.ai-console/blob/main/src/components/backend-ai-console.ts#L1050

Also, If you want to fix this, All you need to do is change that part used in both en.json and ko.json file in resources/i18n directory.

**Comment by swapniljha001** [comment]
Thanks, @lizable for pointing out the necessary files, I have made the required changes. and did a Pull Request for the same.
I am not familiar with Korean, so I wrote the following in the `ko.json` file, is this alright?

` "AboutBackend.AI": "대하여 Backend.AI", `

**Comment by lizable** [comment]
> Thanks, @lizable for pointing out the necessary files, I have made the required changes. and did a Pull Request for the same.
> I am not familiar with Korean, so I wrote the following in the `ko.json` file, is this alright?
> 
> `"AboutBackend.AI": "대하여 Backend.AI",`

Hmm, "Backend.AI에 대하여" would be much more natural expression than "대하여 Backend.AI".
You can simply copy & paste this.

**Comment by swapniljha001** [comment]
Done @lizable.

` "AboutBackend.AI": "Backend.AI에 대하여", `

**Comment by inureyes** [comment]
https://github.com/lablup/backend.ai-console/pull/701
