### ISSUE TITLE
Update manual to explain 'SSH Keypair change' menu

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#695]
* When clicking ? button on left-bottom, there is no ‘SSH Keypair change’ help text.

**Comment by lizable** [comment]
I guess docs of backend.AI console should be updated, to make consistent page based help guide.
SSH Keypair change menu is already implemented, but in summary pages in docs.
(https://console.docs.backend.ai/ko/latest/summary/summary.html#change-ssh-keypair)
How about making a new content page for usersettings?

**Comment by lizable** [comment]
I just updated backend.ai-console docs in order to update the help link of usersettings page, and made a PR for it.
If the PR is merged well, This issue can be solved automatically.

**Comment by inureyes** [comment]
https://github.com/lablup/backend.ai-docs-console/pull/5
