### ISSUE TITLE
Dropdown menu is positioned incorrectly

### ISSUE THREAD

**Issue by Jivvon** [lablup/backend.ai-console#707]
Dropdown menu is positioned incorrectly when the width of window is less than 700px.

![스크린샷 2020-09-10 오후 11 45 11](https://user-images.githubusercontent.com/25628507/92747992-acb3f780-f3bf-11ea-8f34-4b28aa135184.png)

**Comment by inureyes** [comment]
It is resolved with e77282ef35fd967860

**Comment by inureyes** [comment]
Thanks! @Jivvon
