### ISSUE TITLE
Support multi-node multi-GPU on GUI

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#710]
Until now, multi-node / multi-GPU has been demanded mainly by users who use terminals. However, as user demand increases, let's support multi-container bundle function and multi-node and multi-GPU allocation and management based on it in GUI.

Requirements
===========

 * [x] Migrate multi container bundle feature from python SDK to JavaScript SDK
 * [x] Implement resource allocation UI 
 * [x] Add example notebook on example storage
    * [x] NNI examples
    * [x] Horovod examples

**Comment by lizable** [comment]
**Add example notebook on example storage with two options (NNI, Horovod examples)** will be covered in a separate issue.
