### ISSUE TITLE
Resource usage gauge per session

### ISSUE THREAD

**Issue by chris-chris** [lablup/backend.ai-console#771]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

GPU usage 가 뜨지 않습니다.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Go to 'Sessions'
2. See error

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.
<img width="1672" alt="스크린샷 2020-11-03 오전 10 53 22" src="https://user-images.githubusercontent.com/3013964/97937804-084ca100-1dc3-11eb-8c26-a8136323e6d7.png">

**Client:**
 - OS: macOS 10.15.7
 - App version: 20.11.1

**Server:**
 - OS: 18.04.3 LTS (GNU/Linux 4.15.0-121-generic x86_64)
   - Output of `uname -a`: Linux gpuadmin 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Backend.AI version: 20.03.6
 - Python version: 3.7
 - Installation method: on-premise

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by lizable** [comment]
Thank you so much for reporting the bug, @chris-chris !
But I presume that this issue is more appropriate to add `feature` tag instead of `bug`,
since currently usage of resources are covered by RAM and CPU only.
This feature will be applied perhaps in next release.

**Comment by inureyes** [comment]
939c181

**Comment by inureyes** [comment]
Added.
