### ISSUE TITLE
Prevent folder creation/file upload from only read permission

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai-console#777]
**Describe the bug**
The user with only read permission can click upload button although the write operation is not permitted.

**To Reproduce**
※Notice: this bug can be tested with more than one account. (for convenience, account A and B will be used.)
1. Login with account A.
2. Go to Data & Storage page.
3. Click 'NEW FOLDER' button at the right-top of the tab.
4. Folder creation dialog shows.
5. Create Folder with a valid folder name. (e.g. test1)
6. click ![image](https://user-images.githubusercontent.com/46954439/98514038-3131d200-22ac-11eb-9a5d-b56934f19594.png) button in the control panel of the folder created in step 5.
7. Sharing folder dialog shows.
8. type the email address of the account B and click 'share' button.
9. Log out account A and Log in with account B.
10. Go to summary page.
11. see the invitation panel and accept vfolder sharing by account A.
12. Go to Data & Storage page.
13. Click ![image](https://user-images.githubusercontent.com/46954439/98515605-9c7ca380-22ae-11eb-880b-ec713716726f.png) button in the control panel of the folder shared in step 11.
14. Folder explorer dialog shows.
15. Click 'UPLOAD FILE' button or 'CREATE FOLDER' button at the right-top of the dialog.
16-1. When the user clicks 'UPLOAD FILE', dialog shows but uploading file doesn't proceed.
16-2. When the user clicks 'CREATE FOLDER' button, dialog shows but error message shows.

**Expected behavior**
If the user doesn't have a permission for write operation, then button should be disabled to prevent user from clicking buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/46954439/98515288-2f690e00-22ae-11eb-89e6-a5c443e05992.png)

**Client:**
 - OS: macOS 10.15.6
 - App version: 20.11.0
 - Browser version: Firefox 82.0(64 bit)
 - Python version: 3.8.3
 - NodeJS version: 13.8.0

**Server:**
 - OS: macOS 10.15.6
   - Output of `uname -a`: Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Backend.AI version: 20.09.0a2
 - Python version: 3.8.3
 - Installation method: used scripts/install-dev.sh

**Comment by inureyes** [comment]
@lizable  Tooltip location is weird. See attached.

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/949915/99211787-8cb01280-280c-11eb-9e46-4cba1a616e49.png">
