### ISSUE TITLE
Manual kernel image name UI for debug

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#862]
**Is your feature request related to a problem? Please describe.**

To test the kernel pulling / image testing, we need a direct UI to give custom image name to manager.

**Describe the solution you'd like**
Simple debug-only UI for image name textfield

**Describe alternatives you've considered**
혹시 다른 대안들을 생각해본 적이 있다면 함께 적어주세요.

**Additional context**
기능 요청에 대해 보다 잘 이해할 수 있는 다른 맥락을 기술해주세요.

**Comment by lizable** [comment]
This issue has already been raised in #825 by @achimnol
